In [2]:
# importando a biblioteca numpy
import numpy as np

In [3]:
arr = np.arange(0,30,3)

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
# os elementos podem ser acessados por índices como nas listas
arr[3]

9

In [6]:
# para trazer vários elementos pode-se usar os ':'

arr[2:5]

array([ 6,  9, 12])

In [7]:
# todos os elementos anteriores a um elemento sem incluí-lo
arr[:5]

array([ 0,  3,  6,  9, 12])

In [9]:
# todos os elementos posteriores a um elemento incluindo-o
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
# esse tipo de seleção também serve para reatribuição de elementos
arr[2:] = 100

In [11]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
# seleção e slice em arrays de duas dimensões (matrizes)

arr = np.arange(50).reshape((5,10))

In [13]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr.shape

(5, 10)

In [50]:
# dtype retorna o tipo dos elementos da matriz
arr.dtype

dtype('int64')

In [21]:
# notação de dois colchetes
# colchetes com apenas um parâmetro referem-se apenas às linhas
# assim o primeiro colchete faz um slice de linhas enquanto o segundo
# colchete também executa um slice de linhas na matriz resultante

# todas linhas até a linha 3
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
# isso dá no mesmo
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
arr[:][3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [36]:
# notação de vírgula
# expressões à esquerda da vírgula filtram linhas
# expressões à direita da vírgula filtram colunas

arr[1:4, 5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [24]:
# slices de arrays são passados por referência
arr2 = arr[:3]

In [25]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
arr2[:] = 100
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [28]:
# a atribuição feita ao arr2 se extendeu ao arr
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [30]:
# para evitar a passagem de valor por referência usa-se o método copy
arr2 = arr[:3].copy()
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [32]:
arr2[:] = 10
arr2

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [33]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [37]:
# slicing por operações booleanas

bol = arr > 40

In [38]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [62]:
arrEx = np.linspace(0,100,30)

In [63]:
arrEx.shape

(30,)

In [64]:
arrEx = arrEx.reshape(3,10)

In [65]:
arrEx

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [66]:
# para selecionar linhas ou colunas não adjacentes faz-se uso de
# indexação por tuplas
arrEx[:,(0,2)]

array([[ 0.        ,  6.89655172],
       [34.48275862, 41.37931034],
       [68.96551724, 75.86206897]])

In [71]:
# ou ainda por listas (indexação Fancy)
arrEx[[0,2],:]

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])